# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammad Sadegh Majidi Yazdi
title: Undergraduate Student - Computer Engineering
email: sadeghmajidiyazdi@gmail.com
# email_title: Email (Email title override)
phone: (+98) 9361457810
# phone_title: Phone (Phone title override)
website: sadeghmajidi.ir
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: sadegh-majidi
linkedin_username: mohammad-sadegh-majidi-yazdi-602275191

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Mohammad Sadegh Majidi Yazdi. I am studying for a B.Sc. in Computer Engineering at <a href="https://en.sharif.edu/">the Sharif University of Technology</a>. My research interests are:
    - Distributed Systems
    - IoT
    - Computer Networks
    - Operating Systems
    - Computer Architecture
    - Computer Security

  As a computer scientist, I have always enjoyed studying theoretical computer science and getting my hands dirty with mathematics, but I have a special fondness for the practical aspects of computer science. I love to spend consecutive hours trying to understand a challenge in the system and solve it. My ultimate professional goal is to use my knowledge and skills to create something of value for the betterment of the world.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Sharif University of Technology
        caption: September 2019 - February 2024
        sub_title: Bachelor of Science in Computer Engineering
        description: Pursuing a BSc in Computer Engineering at Sharif University of Technology, one of the premier institutions in the region. Achieved an outstanding GPA of 19.24/20, reflecting dedication and academic excellence.
      - layout: left
        title: Mandegar Alborz High School
        caption: Fall 2016 - Summer 2019
        sub_title: High School Diploma in Mathematics and Physics
        description: Completed high school education at Mandegar Alborz High School, one of the oldest and most prestigious institutions in Iran. Graduated with an outstanding GPA of 18.8/20, showcasing my academic prowess and commitment.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Secure Messaging Application
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/sadegh-majidi/Network_Security_Project
        description: Designed and Implemented a secure messaging application using Python as part of the Data & Network Security course. To satisfy a wide range of security measurements, we used a simplified version of the Double Ratchet algorithm and public-private key encryption and concepts like hashing and signing. This project is also well-structured in regard to software development standards.
      - layout: top-middle
        title: Tweet Categorization NLP Project
        description: Implemented a tweet categorization nlp model in C/C++ efficiently to achieve higher performance and speed and lesser resource usage. This model categorizes tweets based on their contents.
      - layout: top-middle
        title: CMinus Compiler
        description: Implemented a Compiler for CMinus Langauge, a simplified subset of the C language, using Python and its standard libraries. The compiler consisted of Lexer, Parser, Code Generator, and Semantic Analyzer.
      - layout: top-middle
        title: MIPS Simulator
        description: Implemented a simplified MIPS processor simulator using Verilog. It supports pipeline and caching.
      - layout: top-middle
        title: SnappFood Minus
        description: An online food ordering and delivery app on Android.
      - layout: top-middle
        title: Online Shop Application
        description: Designed and Implemented a simplified online shop as part of the Advanced Programming course using mainly Java and based on MVC architecture.

  - title: Experiences
    layout: list
    content:
      - layout: left
        title: Yektanet
        role: Software Engineer
        caption: Feb 2021 - Oct 2021 & Oct 2022 - Apr 2023
        description: Yektanet is the largest online advertising company in Iran. As a backend software engineer, I designed and developed online affiliate marketing platform (Chavosh) and product retargeting services using Django, Typescript, Postgresql and redis.
      - layout: left
        title: Gharar
        role: Software Engineer
        caption: Jun 2022 - Aug 2022
        description: As a full-stack software engineer, I developed a new chat system (backend & frontend) for webinars using Django, React, and Lua and I also reduced live streaming latency by properly using HLS protocol over Nginx.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in Distributed Systems, Computer Networks, and Computer Security some of my other interests and hobbies are:
      - Gaming, with a particular fondness for Role-Playing Games
      - Swimming, my favorite sport
      - Listening to music, especially in the Rock and Metal genre

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
