# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 1

# Personal info
name: Wenwen Zhang
title: Graduate Student at University of British Columbia
email: Wenwenzhang@ece.ubc.ca

# Social links
#twitter_username: sproogen
github_username:  Zhang-Wenwen
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: wenw-zhang
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name is Wenwen Zhang, I'm a master student at the University of British Columbia, Canada. 
  I am now working as a research assistant in Flexible Electronics and Energy Lab (FEEL).
  My research focuses on wearable devices and federated learning method considering large proportion of no-label data with huge data heterogeneity at different device end.
  I am very optimistic about the future of wearable devices. I believe the interdisciplinary field which connects the popular machine learning and end devices will be promising. 

  I have worked with a range of different languages (python, MATLAB, C, C++), tried different fields in Electrical Engineering field (microwave components, image process, machie learning), 
  and I am always looking forward to opportunities to work with something new.


# Projects Section
# projects_title: Projects
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Personalized Semi-supervised Federated Learning for Embedded Intelligence
        link: https://feel.ece.ubc.ca/
        # link_text: FEEL
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Flexible Electronics and Energy Lab
        description: | # this will include new lines to allow paragraphs
          Federated learning method considering large proportion of no-label data with huge data heterogeneity at different device end.


# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: |
  When I'm not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
  mountain biking, road cycling, kitesuring and horse riding as well as trying to make time for things like
  rock climbing and playing some rugby. Since my time at university I have become a very keen Kitesurfer and freestyle
  Landboarder. In 2014 I competed and won the amateur landboard British powerkite tour.

  I'm interested in photography and videography as I like to be creative, this is mainly through sport but
  I enjoy landscape and abstract photography too. I like to showcase my work on instagram if
  you would like to take a look - [jameswgrant](https://www.instagram.com/jameswgrant/).

  Finally during the rest of my free time you will either find me working on my bikes, rock climbing at one of
  Bristol's indoor climbing centres or down the Rec supporting Bath Rugby.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
