# Site
repository: ObiMadu/ObiMadu.Github.Io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Obi F.M.
tag: Personal Site
title: Wannabe Web and Software Programmer
email: Bob.Obi@Yahoo.Com
phone: +234 9075855455
website: Https://ObiMadu.Github.Io

# Social links
github_username:  ObiMadu
telegram_username: ObiMadu
twitter_username: jekyllrb
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/profile.png
about_content: | # this will include new lines to allow paragraphs. 
    My name is ___<mark>Obichukwu</mark> <mark>Favour</mark> <mark>Madubuko</mark>___ (Obi Madu, Obi F.M., for short).  
    I'm a born again christian. I recogise _<mark>Jesus Christ</mark>_ who is the only Son of God and saviour of all mankind as my Lord and personal Saviour.
    
    I spend my time serving God through Christ, Learning new things, practicalising some theoritical
    IT based knowledge or speculation with the closest accesible PC i get my hands on, or else
    documeting the little bits of knowledge i've acquired through time, within the IT circle specifically.
    
    I'm interested in Computers and other tech stuff many people refer to as geek.
    I can operate near smoothly on the windows command line, engage the power of the linux bash,
    and live with a GUI.
    
    I operate a bit above the rudiments of the _HTML, CSS and Python_ Programming languages.
    I built this site from scratch in a jekyll production environment.
    I'm a fan of free and open source software.
    
    I started this site as a presentable personal online journal.
    Alot of the grammar in my writeups are unrefined.
    
    However, i write in hope that to the one who lands here with a problem, and one covered 
    here, he/she would be able to find a understandable solution, in a Do-It-Yourself fashion.
    
   

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: My Interests
more_content: | # this will include new lines to allow paragraphs
  This is where i'll write a little more about myself. I could title this section **Interests** and include some of my other interests.

  Or i could title it **Skills** and write a bit more about things that make me more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
