# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Darshan Marde
title: Student
email: darshan.d.marde@gmail.com
# email_title: Email (Email title override)
phone: +91 8767531346
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: x
github_username:  FE-N-X
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: x
linkedin_username: x
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: x
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I’ve always been passionate about **Linux**—there’s something incredibly satisfying about working with an operating system that’s so powerful and flexible. Whether it’s managing systems, writing scripts to automate tasks, or troubleshooting server issues, I love the challenge of making things run smoothly and efficiently. Over time, this interest has grown into a deeper curiosity about **system management** and how to build and maintain infrastructure that’s both reliable and scalable.

 I’m also really drawn to **cloud technologies**. The way platforms like AWS, Azure, and Google Cloud can transform how we build and deploy applications is fascinating to me. I enjoy experimenting with tools like Kubernetes, Docker, and Terraform to see how they can simplify complex processes and make systems more resilient. The cloud feels like the future, and I’m excited to be part of that journey.

 Another area that really captures my attention is **Cybersecurity**. In a world where threats are constantly evolving, I find it incredibly important—and interesting—to learn how to protect systems and data. Whether it’s understanding how hackers think, exploring ethical hacking, or implementing secure practices, I’m always eager to dive deeper into this field and contribute to making technology safer for everyone.

 On top of that, I’m really intrigued by **AI and machine learning**. The idea that we can teach machines to learn from data and solve real-world problems is mind-blowing to me. I’ve been exploring Python, playing around with libraries like TensorFlow and PyTorch, and thinking about how AI can be applied to things like automation, predictive analytics, and even cybersecurity.

 At the end of the day, what I love most is **solving problems**. Whether it’s debugging a tricky issue, optimizing a system, or building something new, I thrive on the challenge of figuring things out. I’m the kind of person who’s always curious, always learning, and always looking for ways to grow. I genuinely enjoy being in environments where I can push myself, learn new things, and contribute to meaningful projects.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Tilak Maharashtra Vidyapeeth
        sub_title: BCA Cloud Computing & Cyber Security
        caption: 2023 - 2026
        quote: >
          The Bachelor of Computer Applications (BCA) is a 3-year undergraduate program that focuses on computer applications and software development. It covers programming languages, database management, web development, software engineering, networking, and computer fundamentals. The course blends theoretical knowledge with practical skills, preparing students for careers in IT and software industries.
        description: | # this will include new lines to allow paragraphs
          To pursue a BCA (Bachelor of Computer Applications), candidates typically need to complete 10+2 or equivalent with Mathematics or Computer Science as a subject. Some institutions may require a minimum percentage (e.g., 50% aggregate) and conduct entrance exams or interviews for admission. The program is open to students from any stream (Science, Commerce, or Arts) with a basic understanding of mathematics and logical reasoning.
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Operating Systems:** Proficient in Linux system administration and troubleshooting.  
      **Cloud Computing:** Hands-on experience with cloud platforms (e.g., AWS, Azure, Google Cloud) and virtualization tools.  
      **Cybersecurity:** Knowledge of network security, vulnerability assessment, and secure system design.  
      **Programming:** Proficient in Python and SQL; familiar with C and Rust.  
      **Databases:** Experience with database management and query optimization using SQL.  
      **AI/ML:** Basic understanding of machine learning concepts and tools (e.g., TensorFlow, scikit-learn).  
      **Tools:** Familiarity with Git, Docker, and shell scripting.  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
